<?xml version="1.0"?>
<robot name="mars_rover_iitb" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <!-- <xacro:include filename="$(find husky_description)/urdf/decorations.urdf.xacro" /> -->
  <xacro:include filename="$(find msi_2k16_17_urdf)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find msi_2k16_17_urdf)/urdf/arm.urdf" />

  <material name="chassis">
    <color rgba="0.67 0.78 0.85 1" />
  </material>

  <property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <property name="base_x_size" value="1.1" />
  <property name="base_y_size" value="0.59" />
  <property name="base_z_size" value="0.35" />


  <!-- Wheel Properties -->

  <property name="wheel_L" value="0.18" />
  <property name="wheel_R" value="0.17" />
  <property name="wheel_length" value="0.18" />
  <property name="wheel_radius" value="0.17" />


  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="1.08" />
  <xacro:property name="track" value="1.0" />
  <xacro:property name="wheel_vertical_offset" value="${-base_z_size/2}" />


    <!-- Base link is the center of the robot's bottom plate -->
  <link name="base_link">
    <visual>
      <geometry>
         <mesh filename="package://msi_2k16_17_urdf/meshes/chassis.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 ${+M_PI/2}"/>
      <material name="chassis"/>
    </visual>
  </link>

  <link name="rocker_left">
     <visual>
      <geometry>
         <mesh filename="package://msi_2k16_17_urdf/meshes/rocker.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="chassis"/>
    </visual>
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="rocker_left_to_chassis" type="revolute">
      <origin xyz=" 0 ${base_y_size/2 + 0.07} 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="rocker_left"/>
      
<limit effort="100" lower="-0.17" upper="0.17" velocity="1"/>
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>

  <link name="rocker_right">
     <visual>
      <geometry>
         <mesh filename="package://msi_2k16_17_urdf/meshes/rocker.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="chassis"/>
    </visual>
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="rocker_right_to_chassis" type="revolute">
      <origin xyz=" 0 ${-base_y_size/2 - 0.02} 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="rocker_right"/>
      
<limit effort="100" lower="-0.17" upper="0.17" velocity="1"/>
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>


  <link name="bogie_left">
    <visual>
     <geometry>
       <mesh filename="package://msi_2k16_17_urdf/meshes/bogie.stl" scale="0.01 0.01 0.01"/>
     </geometry>
      <origin xyz="-0.202 -0.0444 -0.1434" rpy="0 0 0"/>
      <material name="chassis"/>
    </visual>
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="bogie_left_to_rocker" type="revolute">
      <origin xyz="0 0 0 " rpy="0 0 0"/>
      <parent link="rocker_left"/>
      <child link="bogie_left"/>
      
<limit effort="100" lower="-0.17" upper="0.17" velocity="1"/>
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>

  <link name="bogie_right">
    <visual>
     <geometry>
       <mesh filename="package://msi_2k16_17_urdf/meshes/bogie.stl" scale="0.01 0.01 0.01"/>
     </geometry>
      <origin xyz="-0.202 -0.044 -0.1434 " rpy="0 0 0"/>
      <material name="chassis"/>
    </visual>
    <inertial>
      <origin xyz="0 0 1" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="bogie_right_to_roc" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="rocker_right"/>
      <child link="bogie_right"/>      
      
<limit effort="100" lower="-0.17" upper="0.17" velocity="1"/>
      <axis xyz="0 1 0" rpy="0 0 0" />
  </joint>



    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_R}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="33.455" />
        <origin xyz="-0.08748 -0.00085 0.09947" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <origin xyz="0.19 0 0.149" rpy="0 -1.5708 3.1416" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link">
    </gazebo>

    <!-- wheel macros -->
    <xacro:property name="front_left_origin">
   <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:property>
<xacro:property name="front_right_origin">
   <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:property>
<xacro:property name="rear_left_origin">
   <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:property>
<xacro:property name="rear_right_origin">
   <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:property>

    <xacro:husky_wheel wheel_prefix="front_left">
  <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
    <xacro:husky_wheel wheel_prefix="front_right">
<origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:husky_wheel>
    <xacro:husky_wheel wheel_prefix="rear_left" >
 <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:husky_wheel>
    <xacro:husky_wheel wheel_prefix="rear_right">
<origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:husky_wheel>

   <xacro:husky_wheel wheel_prefix="center_left" >
 <origin xyz="0 ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:husky_wheel>
    <xacro:husky_wheel wheel_prefix="center_right">
<origin xyz="0 ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
</xacro:husky_wheel>
    <!-- Decorations MAcro -->
    <!-- <xacro:husky_decorate /> -->



      <xacro:property name="reflect" value="-1" />


      <!-- Join arm -->

     <joint name="jaco_arm_base" type="fixed">
        <parent link="base_link" />
        <child link="base_link1" />
        <origin xyz="${base_x_size -0.7} 0 0" rpy="0 0 0" />
      </joint>



</robot>
